apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault
  includeCRDs: true
  releaseName: vault
  namespace: vault
  version: 0.30.0
  repo: https://helm.releases.hashicorp.com
  valuesInline:
    server:
      ha:
        enabled: false
      readinessProbe:
        enabled: true
        path: '/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204'
      standalone:
        enabled: true
- name: gha-runner-scale-set
  includeCRDs: true
  releaseName: arc-vault
  namespace: vault
  version: 0.11.0
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  # Use values file because the current version of this chart has trouble with the githubConfigSecret value being set as a string here.
  valuesfile: arc-values.yaml

resources:
- sa.yaml
- secrets.yaml
- secretstore.yaml
