apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-secret
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: arc-vault
    kind: SecretStore
  target:
    name: arc-secret
  data:
  - secretKey: github_app_id
    remoteRef:
      key: secret/github/eknudtson/apps/eknudtson-arc-app
      property: app-id
  - secretKey: github_app_installation_id
    remoteRef:
      key: secret/github/eknudtson/apps/eknudtson-arc-app
      property: installation-id
  - secretKey: github_app_private_key
    remoteRef:
      key: secret/github/eknudtson/apps/eknudtson-arc-app
      property: private-key
